server:
  port: 8134

influx:
  org: zoe
  url: http://192.168.0.155:8086
  token: MwKCSUMSoqls9TNRu3ajMNZg9otHMcQewTF57FbiluDX1lhIolm5yoYgLSrJ4sU4_nICkpbCJPX-PNQqFux0Lw==
  bucket: torrents

kafka:
  address: 192.168.0.155:29093
  topic: stats