server:
  port: 8134

influx:
  org: zoe
  url: http://localhost:8086
  token: N2Q7z_WvQhJSr5h2CsIQ_DkMPnw_yAaYYIo17uAeYxx7vW8w_V5VOsWko5vITtHW6skUMrJ6Br52pN6j5n1rrw==
  bucket: torrents

kafka:
  address: localhost:29092
  topic: stats