server:
  port: 8134

influx:
  org: zoe
  url: http://localhost:8086
  token: AErK38IoL5fD_4taxLuwnVSeOvvldO-5xV9VJipZajynUZyCzPsKq5-CI1pXb7zpKO9aa0Ht6BcEOj-e3FROaw==
  bucket: torrents

kafka:
  address: localhost:29092
  topic: stats