server:
  port: 8134

influx:
  org: zoe
  url: http://localhost:8086
  token: VdwECd0CB8IBzchBXROiCFWKD6ADZFregCdtaatOrKEXY3bEfQSlf3MmHthxDzsfI9NuqOBVs7584ihKIw_v-A==
  bucket: torrents

kafka:
  address: localhost:29092
  topic: stats