server:
  port: 8134

influx:
  org: zoe
  url: http://influxdb:8086
  token: AErK38IoL5fD_4taxLuwnVSeOvvldO-5xV9VJipZajynUZyCzPsKq5-CI1pXb7zpKO9aa0Ht6BcEOj-e3FROaw==
  bucket: torrents

kafka:
  address: http://kafka:9092
  topic: stats


spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/torrents
    username: zoe
    password: zoe
  jpa:
    hibernate:
      ddl-auto: update