name: build & publish image

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build image
        run: chmod +x gradlew && ./gradlew bootBuildImage
      - name: Tag & publish
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dpozinen/tracker-stats:latest
